### PR TITLE
Fix error using ILU in parallel

### PR DESCRIPTION
**Pull request by jwallwork23**
A bug was introduced in #276 and reported by @jhill1. Fix suggested by @wence-.

### CODE REVIEW

**Review by stephankramer — DISMISSED** [review]
Makes sense

**Comment by wence-** [comment]
Is that all of them? 4a3d90d0845 seemed to change solver parameters in four places, this only does it in two.

**Comment by jwallwork23** [comment]
Good point. Okay that should do it. `grep -r ilu` only returns `'sub_pc_type': 'ilu'` type entries now.

**Comment by jwallwork23** [comment]
Following discussion in today's meeting, I copied over the infrastructure for running tests in parallel from Firedrake and applied it to some tests. They ran fine and passed for me locally, hopefully they work on the CI, too.

**Review by tkarna — APPROVED** [review]
Thanks! Looks good to me

**Comment by jhill1** [comment]
Pulled this branch and can confirm this works on the local HPC system.

**Pull request merged**
