### PR TITLE
Drone CI configuration

### PR DESCRIPTION
**Pull request by wence-**
Adds a configuration file for drone (hooked up with http://jenkins.ese.ic.ac.uk:8000/thetisproject/thetis).  Let's see if it works!

### CODE REVIEW

**Comment by wence-** [comment]
Sort of works, but it seems to default timeout of 1 hour on drone is not enough...

**Comment by wence-** [comment]
Now that the drone install we have here is 0.5, everything seems much nicer.  So I've ported this forward and merged it.  The full test suite runs including build in a little under an hour, e.g. http://jenkins.ese.ic.ac.uk:8000/thetisproject/thetis/12 and doesn't use any caching (so is "safer" than travis).  The default build timeout is 100 minutes, but I can up this if required.

**Comment by tkarna** [comment]
Looks great! Should we start flagging tests separately for travis and drone? Currently we haven't been able to add more tests as travis will time out.

**Comment by wence-** [comment]
I think we should explicitly mark the tests we want to run on travis.  And by default run everything on drone.

**Comment by wence-** [comment]
At the moment we mark `not_travis` instead.

**Pull request merged**
