### PR TITLE
Solve tracer equation in P1 space

### PR DESCRIPTION
**Pull request by jwallwork23**
This PR includes an option for choosing to solve tracer transport in P1 space, using `solver_obj.options.tracer_family = 'cg'`.

In the current DG setup, problems can arise in the presence of both high diffusivity and element anisotropy (e.g. under anisotropic mesh adaptivity).

### CODE REVIEW

**Comment by tkarna** [comment]
Thanks for this. If tracers are in P1 I think we would need another advection scheme. The SSPRK+slope limiter approach ensures conservation and monotonicity for P1DG tracers, but not for P1. I guess we should use SUPG or something similar, but no such scheme has been implemented yet. Maybe @stephankramer could chime in here.

**Comment by tkarna** [comment]
What are the issues that arise with adaptive mesh and high diffusivity? We currently use interior penalty scheme for stabilizing diffusivity, which might not work very well for highly ansotropic mesh. Thus another approach might be to seek for an alternative method for diffusion.

**Comment by jwallwork23** [comment]
I have been solving an advection-diffusion equation using the `tracer_only` branch with anisotropic mesh adaptivity and have found no problems when diffusivity is <1e-4. However, when diffusivity is greater than this (as large as 0.1 for one test problem I am considering), I often get a DIVERGED_MAX_IT error. I need to look more into to what extent increasing tolerances and max iteration counts and changing convergence criteria can help this. 

Typically, the tracer value on an (often but not always) highly anisotropic element near to the Gaussian profile being advected is significantly different from its neighbours that the mesh adaptive routine throws a lot of resolution there. In some cases this region ends up being more finely meshed than that surrounding the Gaussian. The error then comes when attempting to solve the advection-diffusion equation on this mesh.

**Comment by stephankramer** [comment]
I agree, offering CG advection without any stabilisation is probably not very helpful. A better DG diffusion scheme would be useful indeed but probably requires some more work (@dham, @thomasgibson: anyone tried doing CDG/LDG with slate already?). @jwallwork23 : shall we revisit this when you're back? I can give you some pointers to implement SUPG...

**Comment by jwallwork23** [comment]
@stephankramer : Yes sure, that's something I'd be interested to look at when I get back.

**Pull request closed without merging**
