### PR TITLE
Update publications on website

### PR DESCRIPTION
**Pull request by tkarna**
- Adds two publications for 2021
- Adds Columbia River plume animation on the front page

### CODE REVIEW

**Comment by swarder** [comment]
Added one of mine which has just come out - hope that's OK!

**Comment by tkarna** [comment]
Great, thanks Simon!

**Review by jwallwork23 — APPROVED** [review]
Looks good to me - all the links work.

**Comment by matt-piggott** [comment]
Added two 2021 pubs

**Review by jwallwork23 — APPROVED** [review]

**Pull request merged**
