### PR TITLE
MixedFunctionSpace type no longer user exposed

### PR DESCRIPTION
**Pull request by wence-**
Change required when firedrakeproject/firedrake#713 is merged.

### CODE REVIEW

**Comment by wence-** [comment]
Oops, still wrong. Will fix tomorrow

**Comment by tkarna** [comment]
I think I got the isinstance check working now.

**Comment by tkarna** [comment]
These checks in `momentum_eq.py` are still broken
```
        self.horizontal_dg = ufl_elem._A.family() != 'Lagrange'
        self.vertical_dg = ufl_elem._B.family() != 'Lagrange'
        self.HDiv = ufl_elem._A.family() == 'Raviart-Thomas'
```

**Comment by wence-** [comment]
OK, I'll fix those up now.

**Comment by wence-** [comment]
OK, so these checks are pretty fragile.

For the horizontal_dg and vertical_dg checks, I think the right thing to do is to make the fiat element and check if dofs are only associated with the cell in, respectively, the horizontal and vertical directions.  For the HDiv check, I guess one should check that the outside element is an HDivElement.

**Comment by wence-** [comment]
I've tried to fix the cases where the code was doing checking based on the element family.  I think it should now be more robust (and hopefully work!).

**Comment by tkarna** [comment]
Great, looks good to me!

**Pull request merged**
